### PR TITLE
Topic 4: Translate Priority UI (part 2 / frontend)

### PR DESCRIPTION
**Pull request by imenattatra**
This is a Part of our Redash translation work

## Description
In this PR, we add translation to the left priority part of the UI, it includes:
- The queries list and detail page,  together with the queries snippets
- The user related UI (profile included)

This is deployed in staging and you can check it in these links:
- https://dashboard.staging.metr.systems/staging/queries
- https://dashboard.staging.metr.systems/staging/queries/14/source
- https://dashboard.staging.metr.systems/staging/query_snippets
- https://dashboard.staging.metr.systems/staging/users/me
- https://dashboard.staging.metr.systems/staging/users?order=-created_at&page=1&page_size=20

Please notice that the translation did not include the dynamic forms , which is a component used in users forms and also elsewhere and that will be included in the next translation PR(this is why the words `save` in profil is not yet translated)

## About AntD components translation
You may notice that sometimes I use locale={and put text to translate here} in an antd component, so that i enable and customize translation for that exact component related text but actually antd [offers a better way to translate ](https://ant.design/docs/react/i18n). So far, I only used the strategy mentioned twice and checked that it works ...but I am mentioning it here to get your feedback about it ..to be honest i prefer to keep things as they are for now and just keep in mind that there is another way to do it if needed later ....[still in progress]

## How is this tested?
- [x] Unit tests ( jest)
- [x] Manually

## Related Tickets & Documents
Related issue: https://github.com/metr-systems/backlog/issues/3476

## What is next?
- Dynamic forms and visualisation (less priority but not non-priority translation)
- Backend [needed translations](https://github.com/metr-systems/redash/tree/translate-priority-3-ui/redash/templates)
- Finish with the non-priority translation 

Redash spricht bald Deutsch !

### CODE REVIEW

**Comment by helenalebreton** [comment]
@imenattatra thank you it is looking really good. I went over the pages and have the following questions as it might simply come with the next PR:
- https://dashboard.staging.metr.systems/staging/users/disabled?order=-created_at&page=1&page_size=20 -> 'sorry we couldn't find anyting' is not yet translated
- https://dashboard.staging.metr.systems/staging/queries?order=-created_at&page=1&page_size=20 -> 'Jeden minute' looks like a mix German and english. In German it would be 'Jede Minute'
- https://dashboard.staging.metr.systems/staging/queries/new -> LIMIT 1000 -> in German I would expect something in the line of 'begrenzt auf 1000'
- https://dashboard.staging.metr.systems/staging/users/me -> tooltip on the API key copy icon is still in english
- https://dashboard.staging.metr.systems/staging/queries/14/source -> 
image

**Review by thiagogds — APPROVED** [review]
About the ant design translation I think that it's better to use what they recommend because then all new components will be already translated and you have a central place to set the translation.

I also know that we might need custom translations, but thinking of Redash as an open source project, it's probably better to keep the default ones from the ant design.

I agree with you that it's fine to continue this way, but add an issue for later to come back to this point after. Probably around the time you will work with having a setting for translation on company settings is a good moment to check that again.

**Comment by imenattatra** [comment]
> @imenattatra thank you it is looking really good. I went over the pages and have the following questions as it might simply come with the next PR:
> 
> * https://dashboard.staging.metr.systems/staging/users/disabled?order=-created_at&page=1&page_size=20 -> 'sorry we couldn't find anyting' is not yet translated
> * https://dashboard.staging.metr.systems/staging/queries?order=-created_at&page=1&page_size=20 -> 'Jeden minute' looks like a mix German and english. In German it would be 'Jede Minute'
> * https://dashboard.staging.metr.systems/staging/queries/new -> LIMIT 1000 -> in German I would expect something in the line of 'begrenzt auf 1000'
> * https://dashboard.staging.metr.systems/staging/users/me -> tooltip on the API key copy icon is still in english
> * https://dashboard.staging.metr.systems/staging/queries/14/source ->
>   image

@helenalebreton Thanks for your feedback, they are all fixed and deployed to staging now

**Comment by imenattatra** [comment]
> use antd default translation

Thanks a lot for your feedback @thiagogds , i updated it [here](https://github.com/metr-systems/redash/pull/18/commits/430871d317c22be7d4ffdc8fbc7bd3a875c52554) and we are using antd default translation according to current language now :D

**Comment by helenalebreton** [comment]
@imenattatra thank you for the update. I do not wish to be painfull but nouns in German should have a capital letter and I think we should try to do that too if possible.
Here 
image

the first letter of the noun should be capitalized like s
so 
Minute / Minuten
Stunde / Stunden
Tag / Tage
Woche / Wochen
Monat / Monate

**Comment by imenattatra** [comment]
> @imenattatra thank you for the update. I do not wish to be painfull but nouns in German should have a capital letter and I think we should try to do that too if possible. Here image
> 
> the first letter of the noun should be capitalized like s so Minute / Minuten Stunde / Stunden Tag / Tage Woche / Wochen Monat / Monate

Thanks for the feedback @helenalebreton , no worries, i updated it together[ with the latest PR ](https://github.com/metr-systems/redash/pull/20) and it is deployed to staging

**Pull request merged**
